<?php require_once('template/header.phtml'); ?>
<link rel="stylesheet" href="css/nouislider.css">

<div class="container position-relative d-flex flex-column align-items-center justify-content-center">
    <div id="user_img" class="d-flex flex-column align-items-center justify-content-center gap-2">
        <img src="images/<?php echo $view->active_user_data->getImgUrl(); ?>" alt="Profile Picture" width="150" height="150" class="rounded-circle">
        <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="d-flex gap-2 mb-3" enctype="multipart/form-data">
            <div class="input-group">
                <label class="input-group-text" for="new_dp">New DP</label>
                <input type="file" class="form-control" id="new_dp" name="new_dp" accept="image/*">
            </div>
            <button type="submit" class="btn btn-primary" name="updateProfilePicture">Upload</button>
        </form>
    </div>
    <div class="row w-100 position-relative flex-grow-1">
        <div class="col-12 col-md-6 text-center d-flex flex-column">
            <h3 class="mb-2">Profile Details</h3>
            <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="text-start flex-grow-1 d-flex flex-column">
                <div class="flex-grow-1">
                    <div class="mb-3">
                        <label for="name" class="form-label">Full Name</label>
                        <input type="text" class="form-control" id="fullname" name="fullname" value="<?php echo $_SESSION['active_user']->getFullName(); ?>" required aria-required="true">
                    </div>
                    <div class="mb-3">
                        <label for="phone" class="form-label">Phone Number</label>
                        <input type="text" class="form-control" id="phone" name="phone" value="<?php echo $_SESSION['active_user']->getPhoneNumber(); ?>" aria-describedby="phoneHelp">
                        <div id="phoneHelp" class="form-text">Upto 11 digit phone number</div>
                    </div>
                    <div class="mb-3">
                        <label for="email" class="form-label">Email address</label>
                        <input type="email" class="form-control" id="email" name="email" value="<?php echo $_SESSION['active_user']->getEmail(); ?>" required aria-required="true">
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">New Password</label>
                        <input type="password" class="form-control" id="password" name="password">
                    </div>
                    <div class="mb-3">
                        <label for="confirmPassword" class="form-label">Confirm Password</label>
                        <input type="password" class="form-control" id="confirmPassword" name="confirmPassword">
                    </div>
                </div>
                <button type="submit" class="btn btn-primary" name="updateProfileDetails">Update Profile</button>
            </form>
        </div>
        <div class="col-12 col-md-6 text-center d-flex flex-column">
            <h3 class="mb-2">Charging Point Details</h3>
            <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="text-start flex-grow-1 d-flex flex-column" id="charge_point_form">
                <input type="number" hidden name="lat">
                <input type="number" hidden name="lng">
                <input type="text" name="method" hidden>
                <div class="flex-grow-1">
                    <div class="mb-3">
                        <label for="address1" class="form-label">Address 1</label>
                        <input type="text" class="form-control" id="address1" name="address1" value="<?php if ($_SESSION['active_user']->isOwner()) {
                                                                                                            echo $_SESSION['active_user']->getChargePoint()->getAddress1();
                                                                                                        } else {
                                                                                                            echo "";
                                                                                                        } ?>" required aria-required="true">
                    </div>
                    <div class="mb-3">
                        <label for="address2" class="form-label">Address 2</label>
                        <input type="text" class="form-control" id="address2" name="address2" value="<?php if ($_SESSION['active_user']->isOwner()) {
                                                                                                            echo $_SESSION['active_user']->getChargePoint()->getAddress2();
                                                                                                        } else {
                                                                                                            echo "";
                                                                                                        } ?>" required aria-required="true">
                    </div>
                    <div class="mb-3">
                        <label for="postcode" class="form-label">Post Code</label>
                        <input type="text" class="form-control" id="postcode" name="post_code" value="<?php if ($_SESSION['active_user']->isOwner()) {
                                                                                                            echo $_SESSION['active_user']->getChargePoint()->getPostCode();
                                                                                                        } else {
                                                                                                            echo "";
                                                                                                        } ?>" required aria-required="true">
                    </div>
                    <div class="my-3 d-flex">
                        <h5 class="d-flex align-items-center justify-content-center"><span>Cost</span></h5>
                        <div id="cost-slider" class="mx-5 my-3 flex-grow-1"></div>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text">&#163;</span>
                        <input type="number" class="form-control" name="cost" id="cost" min="0.00" max="10.00" step="0.01" value="<?php if ($_SESSION['active_user']->isOwner()) {
                                                                                                                                        echo $_SESSION['active_user']->getChargePoint()->getCost();
                                                                                                                                    } else {
                                                                                                                                        echo 0;
                                                                                                                                    } ?>" id="cost" name="cost" required aria-required="true">
                        <span class="input-group-text">per kWh</span>
                    </div>
                </div>
                <?php if ($_SESSION['active_user']->isOwner()) {
                    echo '<div class="d-flex flex-wrap gap-2"><button type="button" class="btn btn-primary flex-grow-1" name="updateChargePointDetails">Update Charging Point</button><button type="button" class="btn btn-danger flex-grow-1" name="deleteChargePointDetails">Delete Charging Point</button></div>';
                } else {
                    echo '<button type="button" class="btn btn-primary" name="addChargePointDetails">Add Charging Point</button>';
                } ?>
            </form>
        </div>
    </div>
</div>

<script src="js/nouislider.min.js"></script>
<script src="js/validator.js"></script>
<script async src="https://maps.googleapis.com/maps/api/js?key=<?php require_once('Models/Env.php');
                                                                $env = Environment::load_env();
                                                                echo $env->get_env('GOOGLE_MAPS_API'); ?>"></script>
<script src="js/profile.js"></script>
<?php require_once('template/footer.phtml'); ?>