            </main>


            <div id="footer" class="text-center">
                <p>&copy; Faheem's Borrow my Charger | @00564578 | University of Salford Manchester</p>
            </div>
        </div>
        <!-- Bootstrap core JavaScript
    ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="js/popper.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
    </body>
</html>